# Generated by Django 3.2 on 2022-11-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='institution_code',
            field=models.CharField(default='343634457', max_length=255),
        ),
        migrations.AddField(
            model_name='authority',
            name='nation_code',
            field=models.CharField(default='TR01', max_length=255),
        ),
        migrations.AddField(
            model_name='authority',
            name='sector_code',
            field=models.CharField(default='0016', max_length=255),
        ),
    ]
